server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: postgres

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Identity Service
  message: Identity configuration loaded from GitHub
