server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/order_db
    username: order_user
    password: order_user_password

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Order Service
  message: Order configuration loaded from GitHub
